values:
  - name: "DepotSecret"
    display_name: "An OCI authentication credential for CIQ Depot."
    string_value: "secret://user/depot"
    display_category: "Container"
  - name: "Cores"
    display_name: "How many CPU cores to allocate."
    uint_value: 2
    display_category: "Resources"
  - name: "Memory"
    display_name: "How much memory to allocate."
    string_value: "1GiB"
    display_category: "Resources"
  - name: "Exclusive"
    display_name: "Disallow other jobs from using the same node/instance."
    bool_value: false
    display_category: "Scheduling"
  - name: "Timeout"
    display_name: "Maximum runtime."
    string_value: "12h"
    display_category: "Execution"
  - name: "Volume"
    display_name: "Where to store data."
    string_value: "volume://user/ephemeral"
    display_category: "Storage"
